---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apps-admin
  namespace: media
spec:
  encryptedData:
    PASSWORD: AgABHYkISLSBRopH09ZtvIFig0t1z4HipUWcExiY89OS7HlfeG3hLMJmTVUbOd6efsLN5gBQaVEl4N3MlNZYPVDUZkDshxoskUuqiUOkEQZXuTjlZwTdpirChM3tCiKTswBlPO4n6lLK5tn7xoTvZ/OzUI+YyTfg/6ku7QHs08BOKq9gtZ+9IArpsjxCWrQmt5MPas3DAOyQoC1uecDj5JsX8tEK0JH/25mxlN9MT7KNQIHLi90/+xnZ7PLu6Vb4b+SCO43yN6j+xFvk/Arug1wTQ6F8fy5cYsnC/UyqiOGbTqA1Lqoj/B9oqSWmNrQXWNG5DGhDly+iQVnnY3Fr7Dy9RqdiZ8pM1YXhiltmst+mYW99oqQsoPu5EacblrWszhqPWpfZBygy5PLMcd2dFSlB+TOmLq8tDFhsGUdEsEo7hkkax/ORhy50MIt2LC8aD088cL4GHjbBhSreokundPMt0+TIygCqoyP3UCIBS6o7tfk5sE1p9R5wQkiIRsZN4IZ1s//35rqROrVfdp70BhpsyxuuRDp3GAJeTsvUi7Inoa5/yZ5SmEwWy8JOVb3vhvvz7nuSqlJqFPnR2Se23yDRLVnV7fZZy3hNw2R/pqJvW2bowwiDJHisebrKWzx971iRYLlV6htfqdAsOuiG7BUO4r98ek/K+uBdlh/YXy9lGPEdB4JzsLjLf41GpPYLDwOlpfmJFBbeSw==
    USERNAME: AgBSEgyQgku1B2EjI99h+262se4Z3O5Oc59drF6ZEjF+rH7HLxu7g0KNmKRqJez0ECJcdZrlLCqlgrtLSkfMQ472uzacGbloGJzgE+7XNs4s7ypRmPR85W+flw1dd1nI0wTXp0amt4qKd4pE1F+sr+iORQbeAwBFu+1WcC7UrMBGrOis0RYSgvwrWRdD4nwYnhI2HyrmkF0ohJVDESo+OaGzBHaaJw4hCvzI2kIHs8F1DRul9+I9NqIZaKDo6c4GRPNKm3L3OGO+/3wttTBFg6RS/g1qLzF5XRV6I7jleAmDYoZLyrfGcLNUhTLkg4k+UdMlqNcsiV3g8kjYoZ7pBHzFBOvrl7xfU9hrRYugFrgliWVi3/b+UL0DHPHDW6pVnRC/Hr1TbEZ2Syn+YoPcppAGcPldE/lnz6Q03btfTptxNfPl0s6tGfuD5jB2qOhthd6EVZaZpglvVRDlBmSvqbeasrhXR/RhJAvHqSRdPMHbUNBZME/CnswNCjXU2vjG4OOdijdtLD8IqiaUiSg85TbWUvRVYO1fUEes4Wix5uozNMrJPB6KRvqta+WcKX07BvL09E14PqjIWD/2USUeO9nrtZ/s3GLqxvhO9+zh9q4IgyFjH22iRMj1UVaQiwbNvrH+GR5IQlzoz2X5Gtk44A2liDupl20UNzi2wLSUGUbEuq1YPtaPlIUJZ2+f+zPmlUIeGPeRgw==
  template:
    metadata:
      name: apps-admin
      namespace: media
    type: Opaque
