---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: comicvine
  namespace: media
spec:
  encryptedData:
    COMICVINE_API_KEY: AgDc03LSdryM5CqqTgyMGchiAon2fx3TRmqPThc0uyAQEBbm3dg+GBFl1Qnunij1dCypk7AdiU2UtEKgOlPbJfX3KRn4kYVfKsckaGnqE11OZQlWqbebinZLhjT5VErFjwA6lftGb46OYOtTAl5GdZmRSKT4bJWSIa+1XFQluFt4qDUvRL7OCuPMVHBITWOR44WJLaNr5pjPctV1nEzjyexDVaCkv3hDW7rnZ+CgAECTcHt9Myp4+JU3ukZjnSICjaMZPwlVhuaTNrqWfpYPEHM/BlYoxvkaO+FUcMD1C/7kvGNW+1GCeESir10772Q7E2Bmzw+vyz2pDydoo7KChaa3DtDMmw2+qk/eavHa4TlDUkpGqj4tSno3QXcB8lqVhF6xZ69K4Zx5jjyzhWhLsAwNIbtCwkJS0L8JQti3eUozDH8tAGjHEEHKW0A9WPpTSyPa5fukxmH4MwxTkVSdwJ5LD7Cn05UTB+WjtjKw9iPUWmHesC8afMXQ+xoo0Ogt68ZKbtojKWrtwB/J87hv1dFPxeqvlUafDMYR/pFWzhYsoVJJkC8W6iJybZ8n7KkY6lKsc3pm2ZHFIVB/gDKd7MiwhccC0h8zMEn0syqct9oPuyBhFhe4EeAPjDzfdP5/q6DseySnN7VGYzDgNRPfXGxV3tTcdVGQ/uqY8Anme35geG1eN4txxStHM0WiDmm8i4I/yQ8M4dSHZnWEe5JheI4QgT9Stjs+Lx5iAEeHBLp0nRRym4fzLKTn
  template:
    metadata:
      name: comicvine
      namespace: media
    type: Opaque
