---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-auth
  namespace: media
spec:
  encryptedData:
    WEBUI_PASSWORD: AgACLXHIvlvffJtKwp81DeLaIftQV8Gg2ZCykvDRw+uQCQnwv384AYOvxfeepCf4hALdoAQ4sjHjo+YfWMXvxcFGFY49neMrfuLYThzAbnJJUkIha0NUx7m/fayuj1rkUIG6RVTBVijdmoykBBNwabUnmoWLVrVRp5sbAdsPnF1OcXTLZgDOKDII+x1yy9T7HvA+r15cCh5kho6f7+3U9udmPhHhJmLKn93z3ets8t3Nl7kgtoY7jlGwQfMe/7JXQ84QLmah0zsnnI1mdfUZ3goJAi5w8RngIxwX8mwBdkLUgyws9groM69zUbZ9SaiSljmG8PvijTIlfpDWmtgjOWFQpJ/a6+NA1nqAFGo/S1v5CTgjAGIJWdYgUV9L8H072IrS6DLlb7ERbL08oiUTFqS+cc+LKUFowgR5xKoDBdGiExTkRIOq0jo+jlhsP0fuFem1HC/b+aVah6rnnUiVR0t0uZYL6Rd1917KVkwOVkKWpWDiBO68V+Y7VC/pbm6wti5hhTUcj0aS/8x2oXktgdqih+x+rjgdmj4SSOgxAejHFlxkaN3MaKyiVsQ6FDap/ZptSu2KJ6EN9k45BRvxC6CYGvvq8U04GSR4h/WQl1p0Jaz7tRFi6NkF13/E6TOc8jPYSblSCdQOtUn+Hl2bC7j/yLujmZdXV70Y9B9hBKojdufx0aQZuk6i4YU/rJPmCNfcsr0OF9TN91JFTOppdHme3jEy6IQWnGx2kHuojK1qbw==
    WEBUI_USERNAME: AgAC/GnsA4Sgc7rKxKmj111a9VkYV+UHiUkneIWaLcTlqrSorBGJxNfutoZbCMF/mmBMqiiotnkoCtEcOmdMp7k0iiQaNI+BAh7h6I13X75pm4FUGLl6OJmPphM1qOV35VLXAAjKmBCF959m2uKEsp3tSvg2oqTAaTMw/Mn2RWNu667nHPkDW/v7t+gxoMAH14JSCGrSzXnw6w22txteudgTaaaFAtGYWTtuFZszymYIgvqfYe5h8J/j1mY7LPqhYH9yWTC9pVViVeMawIWsCV9IzkBX2zjEAoPA/oFVoOHShoCqWYNaeBHT4bosQMBlUMO/Lymi8kPQPTKCUuK+huKfJ8Xsmaq7Ok3kflspVRXrFgff587IZVwKKjCZAE8PmEDCnbhDFvgENhpW1mEj69qSA8W3ZpML6+ulu9LqFo6mAFEvq0G7X4Qws5QcDUquTFJl6GY3t76bWqvAwThsvRmYDNy3XkMYi7M3OUOtmfLpnp+pYMumqoBvg7ayIoIgX/o53mr3t2R9qGMIx9SK51+psCFPwer8Aw1MEasrrTUOWvtkIzxH+M62B+9cC81nRbomJnDRuMsH4P/LsCRHLOclTCyUiU7HdVB6yObEDR524upYHq6CtqM+tLJUzQZrB35NRn2wj0TXMspn3/V8xtxTVxUvZEG+BPhn6MVbZxqTYcRzEzKnfNXKPwq0R6sNMPgevg//wQ==
  template:
    metadata:
      name: qbittorrent-auth
      namespace: media
    type: Opaque
