---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-auth
  namespace: media
spec:
  encryptedData:
    WEBUI_PASSWORD: AgARo5q0SUYeB6CyhH6eMtIMzMXuByoDjGru3yPAP4Q5j0ek4JQrshldUoezVtLINDjRE96YsFmXz/SADr6dfwVuQu+yJxx2nzFpKCi8Mqs/uF943wVntBUhr2AIbZ0hch+TLdazIbJGV92wCP0eC7/HvxTNW9R/VJdsH5YJQ3n5bKLe1FzfzxjieZJG81ePe4GCo+qMn2jQvveurpMzZAjXO1phAcNQwW3CyZIZ2vQHxN41OeKhL8VVGRg1UaLRGQc6FUIHuAp+7youOzuRbEN9wnJS0JVh5gh/K2szcQYGKTBq+9hs8gJMoJ+bLZhvlLuXgm7qxD5pFFmgJdaJNQXfLpxODdIHHemhQhg+yxUP0QSdRvPpiHm4Aln+1MAIPkG6hoB8+eWDbnM9676qB1+11nC6bS1wFHUp4UYKwL1LsgJ9QLc72M2Brh6xiL4sdlDziMfKdW18qzhDlGcnagkJ1SZYXsaMkc/RCIvwgM3qtO4H6UkA/BzIhJHTu5x/LyYBcNODOJXaFDl4F/raxPrVAWvQkhR1m+lHn2Y+WNabrRtLh80RBYz7QddFv99r40SkUpEFoJFD581c7E2XY625kXDSdZR8MIRHKZhLAzZVKb9RkglgdnC3HlK9iqPTx0ufsrI2qU94VprKDuzvu4582i/WRjZVlKvU9/Gs/ugmS8Q6aHdiPELS2ndi2YHEomGUa0ZUyMYrnhcjbwpRAguQGRAsrAKNdypgCIieW2NfxQ==
    WEBUI_USERNAME: AgAODPZ4fpNeBM0z8uqeSS245JzMPhmneJ6CR0dW90KXjtONYerKuKyCvwWDAIBjfb4G9o8k8OYKh4z4NE39yPy8iptZhWyvwR7LobgQsKPnQD1biH789Q4CHO6Fce1GE3PCw4Ly45OHXtK4vgqz2SLhMwpBqzp2yNEQR2QqZZn5akTGGslcz4g7PFRTIM5I+AUeN4rQWz2n4QO0JfKVJf7CTd2eENwQjGrZanXNVz3e+obu+Vve76k4it4Dg8h4L86x1eRig8Ai+XvtVHlzOKyX99/H6+KOCs/CtxsGROivrPOtT39/r8fMCS1nIAnx1RsteDW1Qmy4Kc20rWP7HU6KmWsOpAxqMvU6y589OzbOcHQ+3YpqnlxA1YC8Vkxkki5hrQAkLsJCK6N3jK4pbajUVnRpiBUmNyQqiGgvQK7xq9A7xTuda3pVdCQEZt7dwiAZ6jIqb8URzCx2+mNGvieC1XZAhCVeY8C1LGo6J2SvauFZ8LyDuGhI5M5R254d0ZQxbBeUWkwhJWnvT4+idYzvphqgejSOj6uyDmU6FKUdbviQC8mZ7N7r5mw2H5GKtd3Sd/YYCWkGVYr6gx8Ae8AqykfyxBJ1rAGUM1ciAOgE9drsXqSF1k1Y8ONIHlF5UhDQGMskeHVoVvG1IatI+dDr08Sy9cKOX+z2yo1inj5XfhDXoVW+3xBHQV9dyc4gY9xCpvgT4A==
  template:
    metadata:
      name: qbittorrent-auth
      namespace: media
    type: Opaque
