---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-auth
  namespace: media
spec:
  encryptedData:
    WEBUI_PASSWORD: AgDBfckVU+PCtqAeE9WD5mM15oixb71b08flB4e7CdcU1IJlnUp44cTT/bE2UZ1rxVlQUwAmN7XC1OOvu/w5gm2nEdzkuXrsrvmYMqdAq6tn2gUwNKIIhrf36SEUOl3Ap5f9y/mUvHKsgXP05GAWYawZ6CoOUxMJ+IqTv8MHtNtukmUo3/4QAcCikxmGFzzGKsL2Lpu8kFc6ZBRwhJiNhXyFA9wrP+frc+KS04Slxj8DyX5X7i7nfNfXcngRZDOdm3BG9nQ6AQn+w7u82iHML8CsaiZAuXM2tq0T8tdA/O91Ebx2VG4PEe++ArfygZ6vvAcEvxtCS8mptVJkj1nRyMwewba21vJmqr9iVAVUoOcCZJPG66A8yAeRHGwSUCvI9oMZviGxyiu8xfkwhJRWQEJ1/K/YMrP+HynE7MNgSt8BrnIYLicxm0mDpU/lEtsml2y7SuqATC4zzP19+HMRMQM3vViXc62Sv4qpBqJPsmBv1rEYYTyOCLKvTUQi+V6ksUevmw3WDJbrdV+GXgDCBZYL7Gv6b82Tn/InAAUVb1IEI5xk+cnKygeeMbVNW3hOjTzYOY/6LP/SFGrC2WXBEbBXEJGO7AIOVTKDAddtYt4LlEKoL4dmNGFISzKJ8j+sIxOGhpzMEEF4h3KM3bnOyc9dz0krEDjHU/37vm6dQlNEzLTUA3tZfl5xZ1Odf1eePTq+moYHykfFdgBjLO0/L0jVDPbNdql5h7qTGpaWeGPc2w==
    WEBUI_USERNAME: AgCHaJ/GwS2kWLT3/2APT1LaE8yhb8uBd4S0YQxIHgmSKl1DA4gS5kRxzh9eNeuWFAJFgF1HGJ7BElKgQaO1gffCnuoisnZP5iji4EZU/uSm5++vAULFw6v5HhuZc57ml3d8pKPGHNpnyC9ZlfQU+tUhMUqmMQpA2EKM3SJM4GQpkHLDI1J9PvoMEg/y14kfF0j5DIkLTPA+1d0IV5hzuWdKKvKqgDL9ujKTBMqPTSdrn7cfPb8MSi/FtrPCSQwz968pNmor2/LV46gz10hQubH7dLQoRysxh8Bldgj4jqTEFzO5/Fp6s7E2h3WsP898kKff3aw6uwSzUjvKDaznP8cAO59l364Tw3U4GqPoKBCja0iEK4v3HX1gqGxgBfw5pI5008mWMVCtTvxVCp//gRUKdnSFV8wOn2nJ3MoWsUwGxk4z+tWiYcasmUYTbrITKpWRpuuFCAkqiHTJwZuxm4xPnYtxq34vfz+MnG3aqofC8BRWZCk0dP/Tbic9eRa1bg8BAWoiaEsOXUdwHlS+JIH1t3JZQoD4zampq2Bvgd51TPl+KtcCgQbY7sIpIFzz3Jrw3ViYPDQldGNW9xvsQf05IgYsKFD/M6t4MLa5+5b2UIrcPmY5ZW+QYumUWKGRJlGvkHDR9wG0R+wMw2h/kRRVDMhCETHoVByKU2wjzaHC9eP4ao6VjnB0lyHu0KQQ5WN4Ww6NEg==
  template:
    metadata:
      name: qbittorrent-auth
      namespace: media
    type: Opaque
