---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apps-admin
  namespace: media
spec:
  encryptedData:
    PASSWORD: AgCDmaR1rxga4vdv398uNzJeVtuyHev04YFy8QbfF1w+OmK2KlLNizoJs6nD4GxcxQHfMK8wfF6dKanFOJAXqquDMxusEipGcvW0OKJn6oCTGoziNs5+StES20cK1ZB99ZWAEA9ZGclZ+m7VQRfkIRYRc9QqUfWr8mRLcPVf3mPNdHUrPNe1oOJi+vmTeNjCqk6oSLIRtTp+7n+wPO9lfBtQUG0IulYTDIfg7NKcmYVdJNvrrhwtwdpiEyKvvH8wzyS4Zo2AqEVAHhNCBYO1I8Lw6AR30dLOXUNlXbZ6cpLPLxSCdFUPNZCKu0QdXA8TDI4iWOMWfghf0DMUci945yyid3aMxBHHYTXRHFILTdtctzzIITwTyhC8yuRYOOLTWtppPkc1iYmh/veG0AptcBupL2tjO9AXXtW4CYATQku7tlaRp4EFFKwzQtZhkYwF/MnLIscZlB1cuYWZlP3YjD9wikWjNzQJDDA6vaFLytzp4AcTCQwSGMTr4QDo5AOrmbNht3Orm78tFfCJaT2Njk1gu+Z4+Ffy68bAJvViUnj9vgQc7B7bCk+Im99Aqx+F3bkqsg03PrbPhSoeteE2fISixDI+FORPEb7OUsf+Js15D1ueq3/dbNiTO2pVdjFggwo+WrDtdieNkCKr4rJHZirFxpuSn1ct6Ece0VNX4+LXsCEDq7hYPmNppHQ7NcjP5Ojhm7wp8lSckwxOK+BvZYWoDE1IEiwNlk+gbeuNMaVryA==
    USERNAME: AgCTcFx5+mLFpdDV4WqJ6ppqbh7pNM2UaYk+sKSslCezrM435C10rlDBb6ANTnXxT0jHyJyDDhi6hrQ9HRHZ4AP6mF4HEOkGO0dE0VftYsVxQcpjgGJ74n+v+rSJp1kj8ThurWk+KLnrHjBMxl2Nt8V6KcTlHW0p5AxmCeBvh9YODieU97F4+ND5t2fhd8K1NCQq1lxE04QLD+lAeUQTuWOTTd6Zgfepgd3jN3x3ZUZdZiKviFlGWrnQqUsEY/lGuFB0OcnPg1jTir/1L+oCAdqChiY2KJFm3BaZ6ug+gh6as48du7r9uZq8kEbX1k6TlhpOh3BzaqMsAqsFwWP5ozmzmJr+lgi94uaBWjseVYOb+abOnPf6dZtJmUwhCvE8/uLrd4Y8NeYNz1x/XHEXQCqlOKi63fEzwZ5HcaQPryYietRR2bLiBytLQFB0RoccK3gDWponVxRsVgb4t0hxxj8tsFAw9s79u2P7cv1pr8eufttzwZX/8vl4c/H/dZxfEJMMjMtExkMBrxjW8v5ZRmJGFK3BeTuLSQx38MZ08+wmo5aZQPpqpjyCOqN4smdbG4hTbJ3+WBHLGnxy6F/FQqGoOCcYLMHksl9888OO3T0meCqszB28MvgPaIaGsAhLuDl69vt/Gjoica6oL8a1p39NnLAhMQ9/iwZo4FPxmRyViKf9ksYHfT/62DqscU+fw9XZcD8Npw==
  template:
    metadata:
      name: apps-admin
      namespace: media
    type: Opaque
