---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: networking
spec:
  encryptedData:
    TS_AUTHKEY: AgCh7ebPmaCZF70vl5WOhKEMwFLDqC+/3+Wy0YrRN4Yr/Ks8jQD2Fw71M1hkFyTP85+FOOL3eyzLPEi4DrO9R5b4PcFIzPJKuhFwQ04qpk//VozhbTJqjd8TepLe6UqhG2iEY+4G2XBh6KCnmxiURc8llKaRcOUSL0Fqc6yTLy7SAjF5r4g8qAv2SW32M1E8DvoRNLmfmxWGD0t1LiGwAOPX9rXxauiNbkcoAuVD4Uy8BaDfHNwxwnpFlhDI/Bo9+9bKdGopd8OcEtmt31yqmtI6kRkxYiaIRYexSwGULlgy0U5MovPbJcFmsGZfV84djwABo4WylnIsOB/YOmyA7qN+7k5JKnXoR6IJWgEniFWeuBxOMZWv9JhsSeIDEf3NBjBEDzPoL9s3rE2MkWdzqkfXWe7brB4eNQEVY/YiPNNKHHvoNm6SfqZAtHVBOtjcqml9VCAyex734ZvdJAOmzhsgBzbK8J8bgNehnwb2zzJLFnc4qy70gdfFi0YD5vM5ISzGqJunnlHT5E5jD0cJ+Uo88MaIV7gaK2QEIJvWrwKEO0Hfr1z8MCbQhVP/r9uuEAm61I8T+btLnpn6XLmpUGOe+hF9+A5YsW3D/TAjNzjhPVl5OPW2jUXmuY6WH5lNIpNuU0vZKzDrEPMJ7fag/oaiu6a1o3b/EJlryRBxZWadBL/6xuwRetmWXBKrrjhiXR4=
  template:
    metadata:
      name: tailscale-auth
      namespace: networking
    type: Opaque
