---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: networking
spec:
  encryptedData:
    TS_AUTHKEY: AgCcQ5EEuwk7XiOws+rMTOFzIqvBR0Vrp3Foxy1bCP049Cw7FnNK/HaPzi4hmD1zw/SvE+x1a2VzgTBMaWMJLcOwOBvFD3Vu0gAS1oxzeq+1wF0mpyFXGze/f6JDV9/TK93rX/shWR3mMqqfypKK02OYOk71WjI0RHE0plrhENNFYNLD0zp/mqVQYJg3kNmU0V+tg+k4SWLxXaOP048uQrH0wsmt4hn1IBhQEZzpiqAcuAkLKOwAoD+3pNF2jPl0X8aU57OwYJXLflqr7jINocRBOd29sHgJj4RruuUOpd9VVUwXFaOBWDLboV0+3R0OuCRnyGery/dPwonie99lWnsfIJVXyayX2ViEk9MpGBj3tr0ROCLF/V1Ga9fmKLvmkVQUxcoZRLcHQBhSxlwFX68CDCZUhdf4o+DCMaya6PKuGWc8rTsTb3wS4ykL3uE4DhSlbxQ+9+UsgPAKfBdZSvWS46FhKMBHxqUss2eTuIsD36c7jqmozJTP2j5dZ7TDittsX78cS81wdi0fm3iUr2R5enG6uYBVFXLo9uxCMTNXR7g5zmdubmYXSC3+HLf0/6DHm/kLicQ1ERvSVmKupBSF6CYFmoasuMcyupuzDI1nJ/ay4npBNU90KjuStQ1lsngkcMakJbnQF+Ewe/55xjyd7scfC+WKNbKYJRVoTiAyc13eBjhXBZkp4xYzIRqK9j4=
  template:
    metadata:
      name: tailscale-auth
      namespace: networking
    type: Opaque
