---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: networking
spec:
  encryptedData:
    TS_AUTHKEY: AgDZIe+pE6Dm5NtPKi9JoDubl+xi4k2VOLAiVJb6wQ9fRim9+/cxPTScQWdOnjovLd46aLuUfG3H4NdtvDGpR0QMSZVfxFmAzFbwHviP1NokH974sCi6zDWHbOYWQAaDIckRtm24+CuCBazF+TS8ma5cjEauhU9EjNwyVwbdaGzxAn783CBPL+V8KJSAHly7FTdKIYWSTcm62Ao756CYXL3WkcMu8XZ3rEvK9iKKD7OE6hyCfsRMMEyaqFtGZBwU5Uf2jTvOmCgRhUW5ZZVLKL2DgRTahqk+tBQaNICMj4IAe4bVzOR9lAz+TjyRCPL6cl5AZ1imNep+Ll3EeG6p+LKhfVSPfzPQU9FRSyACar9CfeCJKEXcWIolK1YXEfJDI2zT28A6vQ4mBxSUBB2wG+4yCeKYEbeqxf2ax/vD9wwknKH5eatquJQJS27orhSJO+uFIOD7qwD8CqBkUQ05C8Z7s4/fpCDX+gYA8VY5h67UG/lltNvhhV4RtcInyr4HKQq1xl+wz225QxxqJLgAn5YJOUhftoJw9+Kle6vDMD74sCMa6yoXvnRAYk4aKKPzZK2vtT78WrSpxFqg4msWYZXqyDyYrSO2snEs1kZeNcLd+0oDRe//47Idp1XjR88599otB9MF1jU4Q7f4Qd73JaOYQfBvlhcUYcR21T3JlDRmtFDnkPK6ZzhcJwxwx7ZUeyg=
  template:
    metadata:
      name: tailscale-auth
      namespace: networking
    type: Opaque
