---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homarr-secrets
  namespace: media
spec:
  encryptedData:
    SECRET_ENCRYPTION_KEY: AgANh317VuBMnqcZphBflrtw5OgC1nysCyLmf2/7xUmAaxbultTHVQ1aqZGHUgokNBqtrLxDwbtJb5MW1h6ZzlnpE59BMrhYj6GFB8tInfeIHvbuRtEtV2JmNvLUeIJF5DLMnH5Vk7AyKBrqgwGKBE5g2h2bxbzvb0FS3ptyrofgIcobjLFGaF87X/Qn5yl1yI1oNpY4CqY5DJoqKrGUfOLJcT4TUdz2OzQ1giPNFbWs42sxM4PTh1sZhJUPDYvCVJ/EBm9kRTvgroqNJgt3nwP5yT7XkvjcDE2NzB69V+XaibMXBJDZgeaYqjrWFKIQe2XnR6EVNYFuf8aWY/Aw3Ls3ccxbxiUwSqVxKg/IZPwpoMrW5nKylUzm7hSozrnFWD4cvhJBw4ERDa9ACdutgC+UAHKx+z5FL6igKJOSUpgWSDx2ZtCDlixqM1h9r3/CSp+icnr3w8m6Tw2Eq1VkkjwIBcUz9/vMqw/3ERGmgJs8VFdczW2EwKA6/14rhg9eh49dOtM52YJJNTqAHltqBo+2n4VCB6t1gJAuRAjdR2NbW8iQXiKznOCtgY2UDcHIR9ngx5NezrVWwtU2wcOvawv1ZNwOVC+N6ea9PueJ6LPbSlKpSuYMzcBOgPZKmqfOZn51uUk8ur/PNrdy15LP3Fl8xg0BAk7R7OaRCPOIclnVbTPREvLB7l8tJXPxpubb4EAdLp22PFFnjAxfC/DtfAGD63FaZgCrsvtMnDW8tGn+WaIj2osAtz69YlIA8vKyvL1EQX1p+9caU1J9pKFkfW6I
  template:
    metadata:
      name: homarr-secrets
      namespace: media
    type: Opaque
