apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - immich.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: immich-server
      namespace: photos
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: immich-machine-learning
      namespace: photos
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: immich-redis
      namespace: photos
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: immich-postgres
      namespace: photos
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
