{{- range .Values.components }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ .wave | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    {{ if .chart }}
    repoURL: {{ .chart.repoURL }}
    chart: {{ .chart.name }}
    targetRevision: {{ .chart.version | quote }}
    {{ else }}
    repoURL: {{ $.Values.repo.url }}
    targetRevision: {{ $.Values.repo.revision }}
    path: {{ .path }}
    directory:
      recurse: true
    {{ end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
